import * as mongoose from 'mongoose';
import { LexoRank } from 'lexorank';

export default [
  {
    _id: new mongoose.Types.ObjectId('666666666661'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455555').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c0',
    position: LexoRank.min().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId('666666666662'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455555').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c1',
    position: LexoRank.min().genNext().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId('666666666663'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455555').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c2',
    position: LexoRank.min().genNext().genNext().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId('666666666664'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455556').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c3',
    position: LexoRank.min().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId('666666666665'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455556').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c4',
    position: LexoRank.min().genNext().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new mongoose.Types.ObjectId('666666666666'),
    ownerId: new mongoose.Types.ObjectId('222222222233').toString(),
    listId: new mongoose.Types.ObjectId('444444455556').toString(),
    customFieldValues: [],
    attachments: [],
    messages: [],
    checkLists: [],
    members: [],
    labels: [],
    color: '000000',
    status: 'archived',
    description: 'asdadsad',
    title: 'c5',
    position: LexoRank.min().genNext().genNext().genNext().format(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
