export class AppRepository {
  public static USER_REPOSITORY = 'USER_REPOSITORY';

  public static CDR_REPOSITORY = 'CDR_REPOSITORY';

  public static SMS_REPOSITORY = 'SMS_REPOSITORY';

  public static ROLE_REPOSITORY = 'ROLE_REPOSITORY';

  public static PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';

  public static ROLE_PERMISSION_REPOSITORY = 'ROLE_PERMISSION_REPOSITORY';

  public static ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';

  public static MEMBERSHIP_REPOSITORY = 'MEMBERSHIP_REPOSITORY';

  public static MOBIT_INFO_REPOSITORY = 'MOBIT_INFO_REPOSITORY';

  public static PCPOS_PAYMENT_REPOSITORY = 'PCPOS_PAYMENT_REPOSITORY';

  public static FILE_REPOSITORY = 'FILE_REPOSITORY';
}
