export enum Collection {
  USER = 'User',
  PERMISSION = 'Permission',
  ROLE = 'Role',
  BOARD_MEMBERSHIP = 'BoardMembership',
  BOARD = 'Board',
  CARD = 'Card',
  CHECK_LIST = 'CheckList',
  CUSTOM_FIELD_VALUE = 'CustomFieldValue',
  CUSTOM_FIELD = 'CustomField',
  CUSTOM_FORM = 'CustomForm',
  DUE_DATE = 'DueDate',
  FILE = 'File',
  LABEL = 'Label',
  LIST = 'List',
  LOCATION = 'Location',
  MEMBERSHIP = 'Membership',
  MESSAGE = 'Message',
  WORKSPACE = 'Workspace',
  WORKSPACE_CONFIG = 'WorkspaceConfig',
  NOTIFICATION = 'Notification',
  TEMPLATE = 'Template',
  ERROR = 'Error',
  UPDATE_RESOURCE = 'UpdateResource',
  REMOTE_CONFIG = 'RemoteConfig',
}
